### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by CyberShadow** [vpelletier/htail#2]
```console
$ pip install --user htail
Collecting htail
  Downloading https://files.pythonhosted.org/packages/9a/43/211d801728bd162f68899f9277bc2511d80ed1b5fd5ba770f359bc0d64a2/htail-1.3.tar.gz
Installing collected packages: htail
  Running setup.py install for htail ... done
Successfully installed htail-1.3

$ htail https://api.travis-ci.org/v3/job/515955511/log.txt 
Traceback (most recent call last):
  File "/home/vladimir/.local/bin/htail", line 11, in <module>
    load_entry_point('htail==1.3', 'console_scripts', 'htail')()
  File "/home/vladimir/.local/lib/python3.7/site-packages/htail.py", line 362, in main
    ssl.CERT_REQUIRED,
  File "/home/vladimir/.local/lib/python3.7/site-packages/htail.py", line 241, in tail
    stream.write(data)
TypeError: write() argument must be str, not bytes
```

**Comment by vpelletier** [comment]
Thanks for the report, it was indeed badly broken on python 3.

This should be fixed in just-released 1.4 .
